AllCops:
  TargetRubyVersion: 3.1.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Layout/LineLength:
  Max: 120
